Repository AADILcrackstheweb/Trial-Repo-II-CSE-G1, pull requests merged in 2022-10, with the labels that each got.

#4 Added a print statement
  47.c
Labels: hacktoberfest2022, hacktoberfest-accepted

#7 Update 29.c
  29.c
Labels: hacktoberfest2022, hacktoberfest-accepted

#1 Update 55.c
  55.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#24 Update 48.c
  48.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#23 Update 23.c
  23.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#22 Update 54.c
  54.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#21 Update 30.c
  30.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#20 Update 57.c
  57.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#18 Create 25.c
  25.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#17 Update 44.c
  44.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#16 Update 12.c
  12.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#15 Update 8.c
  8.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#14 Update 20.c
  20.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#12 Update 27.c
  27.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#10 Update 17.c
  17.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#9 Update 64.c
  64.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#8 Create 51.c
  51.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#6 Update 56.c
  56.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#3 Update 1.c
  1.c
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted

#25 Update 1.c
  1.c
Labels: enhancement, hacktoberfest2022, hacktoberfest-accepted

#26 Update 66.c
  66.c
Labels: enhancement, hacktoberfest2022, hacktoberfest-accepted

#28 Update README.md
  README.md
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#27 bus tracker
  21Z229 Bus tracker
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted
