Repository AADILcrackstheweb/Trial-Repo-II-CSE-G1, pull requests merged in 2023-10, with the labels that each got.

#29 Update 10.c for hacktoberfest 2023
  10.c
Labels: hacktoberfest-accepted

#30 Update 18.c please accept for hacktoberfest2023
  18.c
Labels: documentation, hacktoberfest-accepted

#31 Update 19.c please accept for hacktoberfest2023
  19.c
Labels: hacktoberfest-accepted

#32 Update 2.c please accept for hacktoberfest2023
  2.c
Labels: hacktoberfest-accepted

#33 Update 11.c Hacktoberfest Update
  11.c
Labels: hacktoberfest-accepted

#34 Update 12.c Hacktoberfest 2023
  12.c
Labels: hacktoberfest-accepted, hacktoberfest2023

#35 Update 12.c hacktoberfest 2023
  12.c
Labels: hacktoberfest-accepted, hacktoberfest2023

#40 Update 21.c for hacktoberfest
  21.c
Labels: hacktoberfest-accepted, hacktoberfest2023

#36 Update 13.c 2023 Hactoberfest
  13.c
Labels: hacktoberfest-accepted, hacktoberfest2023

#39 Update 17.c for hacktoberfest
  17.c
Labels: hacktoberfest-accepted, hacktoberfest2023

#38 Update 13.c for hacktoberfest
  13.c
Labels: hacktoberfest-accepted, hacktoberfest2023

#37 Update and rename 1.c to palindrome.c hacktoberfest accepted
  1.c
  palindrome.c
Labels: hacktoberfest-accepted, hacktoberfest2023

#41 Update 14.c for hacktoberfest
  14.c
Labels: hacktoberfest-accepted, hacktoberfest2023

#42 Update 15.c hacktoberfest accpetance
  15.c
Labels: hacktoberfest-accepted, hacktoberfest2023

#43 LeetCode Problems
  Leetcode/add-two-numbers.md
  Leetcode/contains-duplicate.md
  Leetcode/jump-game.md
  Leetcode/kth-largest-number.md
  Leetcode/swim-in-rising-water.md
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest2023

#46 Added C Programming Notes
  c-programming-notes.md
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest2023

#45 Guide to use Packages in Java
  packages-in-java.md
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest2023

#44 Notes for Important Topics in C
  C Programming/dynamic-memory-allocation.md
  C Programming/functions.md
  C Programming/pointers.md
  C Programming/recursion.md
  C Programming/storage-classes.md
  C Programming/struct.md
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest2023
